CREATE TABLE IF NOT EXISTS `songlib` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `filename` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `path` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `mtime` int(11) NOT NULL DEFAULT '0',
  `size` int(11) NOT NULL DEFAULT '0',
  `md5` varchar(64) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `artist` varchar(255) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `title` varchar(255) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `album` varchar(255) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `trackno` varchar(8) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `year` year(4) NOT NULL DEFAULT '0000',
  `genre` varchar(255) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `comment` varchar(255) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `id3info` text COLLATE utf8_swedish_ci NOT NULL,
  `length` float NOT NULL DEFAULT '0',
  `bitrate` mediumint(9) NOT NULL DEFAULT '0',
  `bitratecl` enum('C','V') COLLATE utf8_swedish_ci NOT NULL DEFAULT 'C',
  `samplerate` mediumint(9) NOT NULL DEFAULT '0',
  `chan` varchar(64) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `rotation` tinyint(4) NOT NULL DEFAULT '0',
  `rating` tinyint(4) NOT NULL DEFAULT '0',
  `flags` varchar(16) COLLATE utf8_swedish_ci NOT NULL DEFAULT '',
  `playcount` int(11) NOT NULL DEFAULT '0',
  `lastupdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastplayed` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `lastseen` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
